### PR TITLE
New QBEC Logo

### PR DESCRIPTION
**Pull request by kvaps**

### CODE REVIEW

**Comment by kvaps** [comment]
Let me know, if you want to change the font/colors

**Comment by gotwarlost** [comment]
Thanks for the PR!

I need to set some expectations on merging this, however....

* we are supposed to have a CLA in place for external contributions and I'm looking into what needs to happen there.

* Also anything that introduces a formal logo for a project probably has legal implications (the current "logo" is just a character from the Unicode character set) and I need to get some other folks involved to make sure this is all good.

**Comment by kvaps** [comment]
I am ready to sign CLA and transfer all the rights on logo to you, no problem.

I just wanted to contribute to my favorite project :)

**Comment by kvaps** [comment]
Ok, done

**Comment by gotwarlost** [comment]
sorry for the delay in responding. Things have been pretty hectic.

**Comment by gotwarlost** [comment]
@kvaps - the new logo looks really awesome on the README and the docs site. Thanks so much!

**Comment by kvaps** [comment]
I'm glad to contribute, thank you for awesome project! ;-)

**Comment by Andor** [comment]
@kvaps Now you have to contribute sources for these logos. In Jsonnet as well :D

**Pull request merged**
