### PR TITLE
Adds support for downloading env files

### PR DESCRIPTION
**Pull request by dan1**
This is a new feature that will allow for downloading extra env files from a remote URL.

### CODE REVIEW

**Comment by harsimranmaan** [comment]
Thanks for the PR @dan1. Can you share a bit about your use case?  IMO, a curl/wget(tooling that is readily available on most systems) might be a better option pull remote files as a standalone action.

**Comment by dan1** [comment]
Hello @harsimranmaan, we would like to allow our service teams to dynamically pull environment files from a remote location.  Although something like curl would work, we also wanted to standardize our deploy scripts.  This would help discourage one team from using curl, and another team using wget, etc.

**Comment by gotwarlost** [comment]
Why do we need a special command for this? I agree that this is not better than curl or wget executed prior to a qbec command.

What we should be supporting is HTTP(s) URLs in the `--env-file <file>` option. Today you can say `--env-file=/local/path/something.yaml` you shoule be able to say `--env-file https://some.server/path/to/env.yaml`

Once we have this in place we _could_ add some more processing _later_ (once this works) to teach qbec to automatically download env files with a template URL or something when an env is not found locally.

**Comment by dan1** [comment]
Thanks @gotwarlost and @harsimranmaan, agreed to move this under the --env-file flag.

**Comment by dan1** [comment]
Will open up a cleaner version of this soon.

**Comment by dan1** [comment]
Will open up a cleaner version of this soon.

**Pull request closed without merging**
