### PR TITLE
introduce data sources, implement exec data source

### PR DESCRIPTION
**Pull request by gotwarlost**
See the demo app at https://github.com/splunk/qbec/tree/dsnext/examples/external-data-app for a quick review of how this works from a user interface viewpoint.

This PR allows data from external sources to be consumed by qbec/ jsonnet. 

This has the following parts:

* An ["external data" importer](https://github.com/splunk/qbec/blob/dsnext/internal/vm/importers/data-source.go) for the jsonnet VM.

This defines a `DataSource` interface that the caller must implement and processes imports of the form `data://<name>[/rest/of/path]` where `name` is the name of the data source and the path is supplied to the data source for resolution.

* An [extended DataSource interface](https://github.com/splunk/qbec/blob/dsnext/internal/datasource/api/api.go) containing lifecycle methods using which a data source can be set up, configured, and torn down.

* A specific [implementation of the data source interface](https://github.com/splunk/qbec/tree/dsnext/internal/datasource/exec) that can execute commands to produce data. This needs to solve the following sub-problems:

  * ability to provide program name, arguments, environment variables and stdin to the command (i.e. potentially a complex JSON configuration). The stdout of running the command is basically the data that is returned to the importer. As usual, this data must be valid JSON if `import` is used and can be any string (e.g. yaml) when `importstr` is used.
  * ability to configure these inputs to the program  based on environment being deployed and other externals defined for the qbec run
  * ability to create a data source on the command line, on the fly

From the user's viewpoint, this works as follows:

* create a data source as `exec://some-name?configVar=varName` - this indicates that a data source named `some-name` is being set up, which is of type `exec`, and gets its configuration from an external code variable called `varName`.
* the var can be passed in as a code variable using std jsonnet arguments. In qbec, It can also be computed on the fly using other externals using the [computed variables feature](https://github.com/splunk/qbec/pull/215). The config is of the form:

```
{
  command: 'program-name',
  args: [ 'list', 'of', 'program', 'arguments' ],
  env: {
     'env-variable1': 'value1',
  },
  stdin: 'some string',
  timeout: '1s',
}
```
where everything except the command is optional. In addition, qbec will also pass in 2 extra environment variables:
* `__DS_NAME__` - the name of the data source
* `__DS_PATH__` - the import path requested by the import invocation.

* Referring to `import 'data://some-name/some/path` will run the defined command and return its stdout as the data.
  Needless to say, the command is expected to behave like a function having no observable side-effects. It definitely should *not* write to the source tree and mess up importer caches. The same version of the command should be used in every invocation etc.

### CODE REVIEW

**Comment by gotwarlost** [comment]
@sbarzowski @harsimranmaan curious to get your thoughts...

**Comment by sbarzowski** [comment]
Interesting! I didn't understand the `exec://some-name?configVar=varName` part. Where is this `exec` going? The rest of the description suggests that only `data://something/a/b/c` will get picked up here?

i think it's important that an API like that offers an easy way to swap or override parts of the config (so that e.g. you can used fixed values for development).

Do you have any specific use cases in mind?

What are the benefits over having an import with `std.extVar('something')` and passing the output of the command as extVar `something`? Is it just about estabilishing a convention for saving defining these external data sources in a file and passing them? That could be quite valuable in itself, but I wonder if there's more to it.

**Comment by gotwarlost** [comment]
So the `exec:://some-name?configVar=varName` is notionally a compact representation of the following JSON:

```
{
    kind: "exec",
   name: "some-name",
  configVar: 'var-name',
}
```

This tells qbec to instantiate a data source that can run commands (kind=exec) and call its `Init` method with the JSON gotten from evaluating `std.extVar('configVar')`

The shorthand form exists to be able to pass this in as a simple command-line argument.

The value of `configVar` is what is used to configure the data source and this could be a fixed JSON for development.

>>> What are the benefits over having an import with std.extVar('something') and passing the output of the command as extVar `something`

The command is evaluated when needed and not every time. So unless someone actually uses the data source as an `import 'data://my-helm-chart/path/tochart.tgz'` (a hypothetical example of expanding an helm chart), the command doesn't need to be eagerly evaluated and set as an external variable.

Also the same command can provide different values based on the `__DS_PATH__` env variable that is set (which flows down from the import definition). This means you could have a generic form of, say, a `vault.sh` command that pulls secrets out of different paths in vault based on how the caller constructs the import.

**Comment by gotwarlost** [comment]
Also note that `exec` is just one possible implementation of a data source. For instance we could write a first class data source for helm charts that uses the Go helm libraries to evaluate charts. That would have to be compiled into qbec or jsonnet and would be defined as a data source called `helm3://<name>?configVar=hemlSpecificConfigVariable`

**Comment by gotwarlost** [comment]
also @kvaps take a look

**Comment by gotwarlost** [comment]
>>> Interesting! I didn't understand the exec://some-name?configVar=varName part. Where is this exec going? The rest of the description suggests that only data://something/a/b/c will get picked up here?

The `exec://some-name` thing is the string that controls what data sources are created by qnec and `data://some-name/some/path` is the use of this data source in jsonnet code

**Comment by gotwarlost** [comment]
I added a test qbec app to show how things are wired together:

https://github.com/splunk/qbec/tree/dsnext/examples/external-data-app

**Review by harsimranmaan — APPROVED** [review]

**Comment by kvaps** [comment]
> also @kvaps take a look

Interesting, can I pass the values for the specific environment as json into stdin?
I would like to use same dataSources for rendering various helm charts for the different environments.

**Comment by kvaps** [comment]
Something like that:

qbec.yaml:
```yaml
  vars:
    computed:
      - name: metricsServer
        code: |
          {
            command: 'sh',
            args: [ '-c', 'helm template "${__DS_NAME__}" ".${__DS_PATH__}" -f-' ],
            stdin: std.manifestJson((import './params.libsonnet').components.metricsServer),
          }
  dataSources:
    - exec://metrics-server?configVar=metricsServer
```

component:
```jsonnet
local renderedChart = importstr 'data://metrics-server/../vendor/bitnami/bitnami/metrics-server';
std.native('parseYaml')(renderedChart)
```

But I would like to use `${__DS_NAME__}` and `${__DS_PATH__}` variables in the stdin

**Comment by kvaps** [comment]
Or alternative version with the hardcoded chart path, but it allows to pass release-name in `"${__DS_PATH__}"`

qbec.yaml:
```yaml
  vars:
    computed:
      - name: metricsServer
        code: |
          {
            command: 'sh',
            args: [ '-c', 'helm template --name-template=\"{{ trimPrefix \\\"/\\\" \\\"${__DS_PATH__}\\\" }}\" vendor/bitnami/bitnami/metrics-server  -f-' ],
            stdin: std.manifestJson((import './params.libsonnet').components.metricsServer),
          }
  dataSources:
    - exec://metrics-server?configVar=metricsServer
```

components/metrics-server.jsonnet:
```jsonnet
local renderedChart = importstr 'data://metrics-server/metrics-server';
std.native('parseYaml')(renderedChart)
```

**Comment by Andor** [comment]
@kvaps https://github.com/splunk/qbec/issues/262

**Pull request merged**
