### PR TITLE
Add a uuid native function

### PR DESCRIPTION
**Pull request by harsimranmaan**
Can also be used as a nonce

### CODE REVIEW

**Comment by sbarzowski** [comment]
Hello, Jsonnet dev here. It's really cool seeing another Jsonnet-based project!

I have a word of warning about this particular change - `uuid` is not a pure function (i.e. returning the same value for the same arguments) and it is likely to cause problems further down the line.

Firstly, the programs using `uuid` may work very differently in future versions of Jsonnet. Because all Jsonnet functions are pure, caching is considered mostly an implementation detail, relevant only for performance. So for example, a future version of Jsonnet may cache `uuid()` and always return the same value for some part of your program.

Second problem is that, with `uuid` you can no longer expect the Jsonnet program to return the same value for the same parameters.  This breaks many useful assumptions that you could otherwise make. For example normally if you change Jsonnet code in one place and reevaluate, you can expect unrelated parts of the output to stay the same. With "functions" like UUID reevaluation may cause diffs all over the place (which may in turn trigger unnecessary redeployments if the Jsonnet code describes "desired state").

Of course it's not my project, so it's just some unsolicited advice.

**Comment by harsimranmaan** [comment]
Thanks @sbarzowski. I see your point. I have been using a UUID as extvar where I need it mostly for local dev env. There is no pressing reason to introduce a non deterministic function to qbec jsonnet as it is just a convenience. I think that your advice is valuable. Will think more about this

**Comment by gotwarlost** [comment]
@sbarzowski thank you for your comments. Please take this as an open invitation to comment on any and all qbec PRs. Your comments are very much solicited!

I completely agree that this breaks the hermetic properties of jsonnet and we shouldn't be adding this. I have consciously broken this property in the `expandHelmTemplate` native function that qbec supports given that it doesn't use helm as a library but runs the process externally due to which the data it gets is highly dependent on the helm version being used. 

However, that function was so important for a number of use-cases that I decided to include it anyway. Always thought of adding a guard where people can specify a semver range of acceptable helm versions to be confident about its output but never did get around to it.

@harsimranmaan what is the use-case where you need a uuid? I think it is actually better to do a md5/ sha256 sum on the data you are dependent on (we use this trick to inject an environment variable in the pod template based on the hash of the config map data it depends on such that changes to the config map cause the pod to be redeployed).

**Comment by gotwarlost** [comment]
closing due to the comments above.

**Pull request closed without merging**
