### PR TITLE
Add qbec.io/component as label

### PR DESCRIPTION
**Pull request by korroot**
Add component as a label, not only annotation to Kubernetes objects.

Add componentLabel as CLI parameter for backward compatibility
    
In order to decide if add component name as label to k8s objects, there is a CLI parameter called --component-label.
By default it is set to false, and only after passing --component-label argument to qbec it adds 'qbec.io/component' as label.

This addresses #180

### CODE REVIEW

**Comment by korroot** [comment]
@gotwarlost @harsimranmaan any thoughts on my PR?

**Review by harsimranmaan — APPROVED** [review]
Thank you for the contribution @korroot 🎉. lgtm. @gotwarlost do you think that the component label can be set by default?

**Comment by gotwarlost** [comment]
Sorry for the delay in response. I've been pretty slammed with other things.

Some history - The reason `component` is an annotation and not a label is that we never want to use it as a label selector in the qbec GC flow and my idea was that we should prefer annotations to labels when possible since label values have length and character restrictions. It is ok to say that environment and application name should be valid qbec labels but it seemed unreasonable to me that we should introduce such restrictions on component naming especially since qbec doesn't need it.

That said, I'm open to an PR that _also_ adds the component label as long as it doesn't break the qbec interface and is 100% opt-in. This PR is that so it satisfies these criteria.

However, I think the implementation should not be a command line flag that people need to remember to set for every invocation but a boolean attribute in qbec yaml (say, `addComponentLabel` defaulting to `false`). This will ensure that the component label is always even when different people run the command.

**Comment by gotwarlost** [comment]
* Change the swagger schema: https://github.com/splunk/qbec/blob/master/internal/model/swagger.yaml
* Regenerate the JSON using `gen-qbec-swagger` (we should porobably add a make target to facilitate this)
* Add a method to the App object that wraps the QbecApp object
* Use it where needed

**Comment by gotwarlost** [comment]
Oh and add it to the reference doc page: https://github.com/splunk/qbec/blob/master/site/content/reference/qbec-yaml.md

**Comment by korroot** [comment]
Thanks for review. I like the idea about config file where to set if component should be able added as a label.
I will work on the comments and return in some 2 weeks (after New Year).

**Comment by hudymi** [comment]
@gotwarlost I have contacted @korroot, and I will continue the work on this. Please take a look if the provided changes are something that you expected as a valid solution. Thanks :smile:

**Comment by gotwarlost** [comment]
LGTM. The only issue I see is that we have made an already ugly signature of `model.NewK8sLocalObject` even uglier by adding the bool. That said, we can fix that as a refactor in a later PR.

I'm merging this.

**Comment by gotwarlost** [comment]
Now available in the `v0.13.3` release: https://github.com/splunk/qbec/releases/tag/v0.13.3

Thank you @korroot and @hudymi for your contribution and happy holidays!

**Pull request merged**
